---
deployment:
  tasks:
    - export SITE_DIR=/home/khehlacl/public_html/khehlacleanings.co.za

    # Create the directory if missing
    - mkdir -p $SITE_DIR

    # Clean old files
    - /bin/rm -rf $SITE_DIR/*

    # Copy all project files to this domain's folder
    - /bin/cp -R * $SITE_DIR

    # Set permissions
    - /bin/find $SITE_DIR -type d -exec chmod 755 {} \;
    - /bin/find $SITE_DIR -type f -exec chmod 644 {} \;
